[package]
name = "lemmy_db_views"
version = "0.1.0"
edition = "2018"

[lib]
doctest = false

[dependencies]
lemmy_db_queries = { path = "../db_queries" }
lemmy_db_schema = { path = "../db_schema" }
diesel = { version = "1.4.7", features = ["postgres","chrono","r2d2","serde_json"] }
serde = { version = "1.0.126", features = ["derive"] }
log = "0.4.14"
url = "2.2.2"

[dev-dependencies]
serial_test = "0.5.1"
