[package]
name = "lemmy_server"
version = "0.0.1"
edition = "2018"

[lib]
doctest = false

[profile.dev]
debug = 0

[workspace]
members = [
    "crates/api",
    "crates/api_crud",
    "crates/api_common",
    "crates/apub",
    "crates/apub_receive",
    "crates/utils",
    "crates/db_queries",
    "crates/db_schema",
    "crates/db_views",
    "crates/db_views_actor",
    "crates/db_views_actor",
    "crates/websocket",
    "crates/routes"
]

[dependencies]
lemmy_api = { path = "./crates/api" }
lemmy_api_crud = { path = "./crates/api_crud" }
lemmy_apub = { path = "./crates/apub" }
lemmy_apub_receive = { path = "./crates/apub_receive" }
lemmy_utils = { path = "./crates/utils" }
lemmy_db_schema = { path = "./crates/db_schema" }
lemmy_db_queries = { path = "./crates/db_queries" }
lemmy_db_views = { path = "./crates/db_views" }
lemmy_db_views_moderator = { path = "./crates/db_views_moderator" }
lemmy_db_views_actor = { path = "./crates/db_views_actor" }
lemmy_api_common = { path = "crates/api_common" }
lemmy_websocket = { path = "./crates/websocket" }
lemmy_routes = { path = "./crates/routes" }
diesel = "1.4.7"
diesel_migrations = "1.4.0"
chrono = { version = "0.4.19", features = ["serde"] }
serde = { version = "1.0.126", features = ["derive"] }
actix = "0.12.0"
actix-web = { version = "4.0.0-beta.8", default-features = false, features = ["rustls"] }
log = "0.4.14"
env_logger = "0.8.4"
strum = "0.21.0"
url = { version = "2.2.2", features = ["serde"] }
openssl = "0.10.35"
http-signature-normalization-actix = { version = "0.5.0-beta.6", default-features = false, features = ["sha-2"] }
tokio = { version = "1.8.0", features = ["sync"] }
anyhow = "1.0.41"
reqwest = { version = "0.11.4", features = ["json"] }
activitystreams = "0.7.0-alpha.11"
actix-rt = { version = "2.2.0", default-features = false }
serde_json = { version = "1.0.64", features = ["preserve_order"] }
clokwerk = "0.3.5"

[dev-dependencies.cargo-husky]
version = "1.5.0"
default-features = false # Disable features which are enabled by default
features = ["precommit-hook", "run-cargo-fmt", "run-cargo-clippy"]
