[package]
name = "lemmy_api_crud"
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
homepage.workspace = true
documentation.workspace = true

[dependencies]
lemmy_apub = { workspace = true }
lemmy_utils = { workspace = true }
lemmy_db_schema = { workspace = true, features = ["full"] }
lemmy_db_views = { workspace = true, features = ["full"] }
lemmy_db_views_actor = { workspace = true, features = ["full"] }
lemmy_api_common = { workspace = true, features = ["full"] }
lemmy_websocket = { workspace = true }
activitypub_federation = { workspace = true }
bcrypt = { workspace = true }
serde_json = { workspace = true }
serde = { workspace = true }
actix-web = { workspace = true }
tracing = { workspace = true }
url = { workspace = true }
async-trait = { workspace = true }
webmention = "0.4.0"
#reqwest = { version = "0.11.10", features = ["json"] }
reqwest-middleware = { version = "0.1.5" }
uuid = { version = "1.1.2", features = ["serde", "v4"] }
chrono = { version = "0.4.19", features = ["serde"], default-features = false }
sha2 = "0.10.6"
[dev-dependencies]
