[package]
name = "lemmy_db_views_moderator"
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
homepage.workspace = true
documentation.workspace = true

[lib]
doctest = false

[features]
full = ["lemmy_db_schema/full", "diesel", "diesel-async"]

[dependencies]
lemmy_db_schema = { workspace = true }
diesel = { workspace = true, features = ["postgres","chrono","serde_json","uuid"], optional = true }
diesel-async = { workspace = true, features = ["postgres", "bb8"], optional = true }
serde = { workspace = true }
uuid = { workspace = true, features = ["serde", "v4"] }
