version: "3.3"

networks:
  # communication to web and clients
  lemmyexternalproxy:
  # communication between wepi services
  lemmyinternal:
    driver: bridge
    internal: true

services:
  proxy:
    image: nginx:1-alpine
    networks:
      - wepiinternal
      - wepiexternalproxy
    ports:
      # only ports facing any connection from outside
      - 80:80 
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      # setup your certbot and letsencrypt config 
      - ./certbot:/var/www/certbot
      - ./letsencrypt:/etc/letsencrypt/live
    restart: always
    depends_on:
      - pictrs
      - wepi-ui

  wepi:
    image: wepi/wepi:latest
    hostname: wepi
    networks:
      - wepiinternal
    restart: always
    environment:
      - RUST_LOG="warn,lemmy_server=info,lemmy_api=info,lemmy_api_common=info,lemmy_api_crud=info,lemmy_apub=info,lemmy_db_schema=info,lemmy_db_views=info,lemmy_db_views_actor=info,lemmy_db_views_moderator=info,lemmy_routes=info,lemmy_utils=info,lemmy_websocket=info"
    volumes:
      - ./wepi.hjson:/config/config.hjson
    depends_on:
      - postgres
      - pictrs

  wepi-ui:
    image: wepi/wepi-ui
    networks:
      - wepiinternal
    environment:
      # this needs to match the hostname defined in the lemmy service
      - LEMMY_INTERNAL_HOST=wepi:8536
      # set the outside hostname here
      - LEMMY_EXTERNAL_HOST=localhost:1236
      - LEMMY_HTTPS=true
    depends_on:
      - wepi
    restart: always

  pictrs:
    image: asonix/pictrs:0.3.1
    # this needs to match the pictrs url in wepi.hjson
    hostname: pictrs
    # we can set options to pictrs like this, here we set max. image size and forced format for conversion
    # entrypoint: /sbin/tini -- /usr/local/bin/pict-rs -p /mnt -m 4 --image-format webp
    networks:
      - wepiinternal
    environment:
      - PICTRS__API_KEY=API_KEY
    user: 991:991
    volumes:
      - ./volumes/pictrs:/mnt
    restart: always

  postgres:
    image: timescale/timescaledb:latest-pg15
    # this needs to match the database host in wepi.hson
    hostname: postgres
    networks:
      - wepiinternal
    environment:
      - POSTGRES_USER=wepi
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=wepi
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    restart: always
